### PR TITLE
Updating the home page based on the feedback

### PR DESCRIPTION
**Pull request by ashokirla**
This pr fixes the home page for PetStore website. We are adding:

- Category wise listing of all the pets.
- Ability to sort based on the prices and ratings
- Search functionality
- Basic info for each of the pets in the form of contextual popups.

All the api and integration tests are included in the same PR. The pr also contains code coverage details.

### CODE REVIEW

**Review by abhishekhegde — CHANGES_REQUESTED** [review]
Need to add autosuggest in search

**Comment by abhishekhegde** [comment]
Need to add autosuggest in search

**Review by abhishekhegde — APPROVED** [review]
Looks good!

**Comment by ashokirla** [comment]
New comment

**Pull request merged**
